### ISSUE TITLE
how to use with customized model

### ISSUE THREAD

**Issue by bing0037** [chenjoya/dropit#2]
I have a [vgg16](https://github.com/pytorch/vision/blob/main/torchvision/models/vgg.py) model and want to do the dropit operation to reduce GPU memory consumption during training. 
I added the following code before training:
```
model = vgg16()

from dropit import to_dropit
model = to_dropit(model, strategy='mink', gamma=0.9)

# do training
```

However, I got the same GPU memory consumption with or without dropit. Is any additional step that I should do to achieve memory reduction?

Thanks!

**Comment by chenjoya** [comment]
Hi bing0037,

Currently, we only support memory efficiency in transformers. ConvNet is difficult to save memory in practice since it has shared memory between relu and conv:

ReLU (inplace) -> (save cache) -> Conv

But transformer architecture does not have this problem. You can try [vit](https://github.com/pytorch/vision/blob/main/torchvision/models/vision_transformer.py) and I believe it would be okay.

Best,
Joya
